spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
  google:
    storage:
      bucketName: ${GCS_BUCKET_NAME}
      adminJsonPath: ${GCS_ADMIN_JSON_PATH}